spring:
    data:
        mongodb:
          database: iot
          port: 27017
          host: ${MONGO_HOST:localhost}
    mvc:
        pathmatch:
          matching-strategy: ant-path-matcher
server:
  port: 8082
